apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageauthor
  labels:
    app: manageauthor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manageauthor
  template:
    metadata:
      labels:
        app: manageauthor
    spec:
      containers:
        - name: manageauthor
          image: "a0717.azurecr.io/manageauthor3:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
